---
- name: Updating system repositories (Debian)
  apt:
    update_cache: yes
  become: true

- name: Installing unzip package (Debian)
  apt:
    name: unzip
    state: present
  become: true
  register: task_result
  until: task_result is succeeded
  retries: 5
  delay: 5
