---
- name: Checking consul hosts are defined or not
  fail:
    msg: "Playbook execution failed due to missing or empty required group 'consul'"
  when: groups['consul'] is not defined or groups['consul'] | length == 0

- name: Checking OS compatiblity
  fail:
    msg: >
      This role is supported with Debian family for now.
      RedHat support is under construction
  when:
    ansible_os_family != "Debian"
