---
- name: Configuring the Consul Server in /etc/hosts
  blockinfile:
    block: |
      {{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ item }}
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  become: true
  with_items:
    - "{{ groups['consul'] }}"

- name: Setting up hostname of Consul nodes
  hostname:
    name: "{{ inventory_hostname }}"
  become: true
